# ========================
# Server Config
# ========================
server.port=8081

# ========================
# PostgreSQL Database
# ========================
spring.datasource.url=jdbc:postgresql://localhost:5432/smarterp_db
spring.datasource.username=postgres
spring.datasource.password=mentixora123
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / Hibernate
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ========================
# JWT Secret (change this!)
# ========================
jwt.secret=smarterp_super_secret_key_change_in_production_2025
jwt.expiration=86400000

# ========================
# Swagger
# ========================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ========================
# App Info
# ========================
spring.application.name=smarterp-backend
spring.jpa.open-in-view=false
logging.level.org.springframework.security=DEBUG